# Generated by Django 4.2.30 on 2026-05-11 04:00

import django.core.validators
from django.db import migrations, models
import envios.validators


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomienda',
            name='tags',
            field=models.CharField(blank=True, default='', help_text='Etiquetas separadas por coma', max_length=200),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='codigo',
            field=models.CharField(max_length=20, unique=True, validators=[envios.validators.validar_codigo_encomienda]),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='peso_kg',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[envios.validators.validar_peso_positivo, django.core.validators.MinValueValidator(0.01, message='El peso mínimo es 0.01 kg')]),
        ),
    ]
