# Generated by Django 4.2.30 on 2026-05-11 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0002_encomienda_tags_alter_encomienda_codigo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('importante', models.BooleanField(default=False)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentarios_internos', to='envios.empleado')),
                ('encomienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='envios.encomienda')),
            ],
            options={
                'verbose_name': 'Comentario interno',
                'verbose_name_plural': 'Comentarios internos',
                'db_table': 'comentarios_internos',
                'ordering': ['-fecha'],
            },
        ),
    ]
