# Generated by Django 4.2.30 on 2026-05-11 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('envios', '0003_comentariointerno'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncomiendaFavorita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('encomienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='envios.encomienda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'encomienda_favoritas',
                'ordering': ['-fecha'],
                'unique_together': {('usuario', 'encomienda')},
            },
        ),
    ]
