# Generated by Django 4.2.30 on 2026-05-13 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0005_tarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único (ej: VERANO2026)', max_length=20, unique=True)),
                ('descripcion', models.CharField(blank=True, default='', max_length=200)),
                ('tipo', models.CharField(choices=[('PCT', 'Porcentaje (%)'), ('FIJ', 'Monto fijo (S/)')], default='PCT', max_length=3)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Porcentaje (1-100) o monto en S/', max_digits=10)),
                ('usos_maximos', models.PositiveIntegerField(default=0, help_text='0 = ilimitado')),
                ('usos_actuales', models.PositiveIntegerField(default=0)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cupones',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='encomienda',
            name='descuento_aplicado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='estado_pago',
            field=models.CharField(choices=[('PEN', 'Pendiente'), ('PAG', 'Pagado'), ('DEV', 'Devuelto')], default='PEN', max_length=3),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('EFE', 'Efectivo'), ('YAP', 'Yape'), ('PLI', 'Plin'), ('TRF', 'Transferencia'), ('TAR', 'Tarjeta'), ('CTR', 'Contra entrega')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='cupon_aplicado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encomiendas_usadas', to='envios.cupon'),
        ),
    ]
