# Generated by Django 4.2.30 on 2026-05-08 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('VIEW', 'Consulta de perfil'), ('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('SEARCH_DNI', 'Búsqueda por DNI (RENIEC)')], max_length=20)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('detalle', models.CharField(blank=True, max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos_log', to='clientes.cliente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos_clientes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acceso a cliente',
                'verbose_name_plural': 'Accesos a clientes (auditoría)',
                'db_table': 'acceso_cliente_log',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['-fecha'], name='acceso_clie_fecha_79cdc6_idx'), models.Index(fields=['usuario', '-fecha'], name='acceso_clie_usuario_476cfe_idx'), models.Index(fields=['cliente', '-fecha'], name='acceso_clie_cliente_bb0e21_idx')],
            },
        ),
    ]
